NAME = libft.a
CC = CC
CFLAGS = -Wall -Wextra -Werror
LIBFT = ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigits.c ft_isprint.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c 
        ft_memset.c ft_strchr.c ft_strlcat.c ft_strlcpy.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_tolower.c ft_toupper.c ft_strdup.c
ADDS = 
BONUS =
